### ISSUE TITLE
More flexible and generic mission yamls

### ISSUE THREAD

**Issue by Archina** [Varzeki/mobot#3]
To make mission submission more flexible I purpose a new format for the mission yamls.
The outcome can be evaluated with the eval() method of ruby. The attribute tags can be replaced with the according character attributes.

```yaml
title: Mission title
info: Short mission description text of how the mission started.
authors: [ Archina, Undertaker ]
attr: [ DEX ] # This may be obsolete with the attribute outcome within the outcomes array.
difficulty: Medium
outcomes:
  - chance: 0.7 # A percent or weight based value can be used to describe the likelihood of outcomes.
    text: Description of a positive outcome for the party/character.
    outcome: 70 + 7 DEX + 2 LCK
  - text: Description of a negative outcome for the party/character.
    outcome: LCK - 70 # A negative value will result in a loss of money.
```
